name: Infrastructure Deployment and Configuration

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TF_WORKSPACE: "production"

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Copy ssh key
        run: |
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > terraform/ssh_key.pub
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > terraform/ssh_key.pem
          chmod 600 terraform/ssh_key.pem

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform format
        run: |
          cd terraform
          terraform fmt -check
      
      - name: Terraform validate
        run: |
          cd terraform
          terraform validate
  
      - name: Terraform plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color -input=false
        continue-on-error: true
      
      - uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
  
            <details><summary>Show Plan</summary>
  
            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`
  
            </details>
            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
  
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
  
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
  
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false

      - name: Extract Server IP
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          cd terraform
          echo "SERVER_IP=$(terraform output -raw instance_public_ip)" >> $GITHUB_ENV
          echo "Server IP is ${{ env.SERVER_IP }}"

      - name: Wait for instance to be SSH ready
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          timeout 300 bash -c 'while ! nc -z ${{ env.SERVER_IP }} 22; do sleep 1; done'

  ansible:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Python
        run: sudo apt-get update && sudo apt-get install -y python3-pip

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Create Ansible Inventory
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          echo "[webservers]" > inventory.ini
          echo "${{ env.SERVER_IP }} ansible_user=ubuntu ansible_ssh_private_key_file=terraform/ssh_key.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'" >> inventory.ini

      # - name: Setup SSH Key
      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      #   run: |
      #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key.pem
      #     chmod 600 ssh_key.pem

      - name: Run Ansible Playbook
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          APP_DIR: ${{ vars.APP_DIR }}
          APP_NAME: ${{ vars.APP_NAME }}
          APP_USER: ${{ vars.APP_USER }}  
          REPOSITORY: ${{ vars.REPO }}
          NODE_VERSION: ${{ vars.NODE_VERSION }}
          BUILD_DIR: ${{ vars.BUILD_DIR }}
        run: |
          ansible-playbook -i inventory.ini ansible-config/main.yaml

      - name: Cleanup Sensitive Files
        if: always()
        run: |
          rm -f ssh_key.pem inventory.ini
